# Generated by Django 5.0.8 on 2024-08-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='User_Auth_u_usernam_9fb935_idx',
        ),
    ]
