# Generated by Django 5.0.8 on 2024-08-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0002_remove_user_user_auth_u_usernam_9fb935_idx'),
        ('User_Auth', '0029_merge_0017_alter_user_dob_0028_alter_user_dob'),
        ('User_Auth', '0031_alter_user_phone_no'),
    ]

    operations = [
    ]
