# Generated by Django 5.0.8 on 2024-09-05 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0038_userdeletedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdeletedata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Auth.user'),
        ),
    ]
