# Generated by Django 5.0.8 on 2024-09-05 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0039_alter_userdeletedata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeletedata',
            old_name='deleted_at',
            new_name='deleted_date',
        ),
    ]
