# Generated by Django 5.0.8 on 2024-09-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0040_rename_deleted_at_userdeletedata_deleted_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDeleteData',
        ),
    ]
