# Generated by Django 5.0.8 on 2024-09-05 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0041_delete_userdeletedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeleteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_Auth.user')),
            ],
        ),
    ]
