# Generated by Django 5.0.8 on 2024-08-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0032_merge_20240821_1214'),
        ('user_connection', '0002_blockeduser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together={('blocker_id', 'blocked_id')},
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocked_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_to', to='User_Auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocker_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_from', to='User_Auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocker',
        ),
    ]
